### PR TITLE
dev-toolkit v6 - The Journey of how version 6 came to be

### PR DESCRIPTION
**Pull request by stoikerty**
This PR is where future work for the next version of dev-toolkit will be merged into.

It's all in experimental stage until I can make sure that it's possible to use neutrino for everything that dev-toolkit currently offers. The goal is to migrate to webpack 2 while (hopefully) allowing the possibility to extend dev-toolkit with neutrino presets. The final release of webpack 2 [is official](https://medium.com/webpack/webpack-2-2-the-final-release-76c3d43bf144) and [`import()`](https://github.com/tc39/proposal-dynamic-import) is getting finalised, therefore the time has come to upgrade and bring the future closer once again.

This PR will be a long-running one since every functionality is affected. A large percentage of plugins will have to be migrated to their newest versions and there will surely be incompatibilities along the way. We'll see how it goes.

### CODE REVIEW

**Comment by stoikerty** [comment]
There's an interesting Article by Airbnb called "[Rearchitecting Airbnb’s Frontend](https://medium.com/airbnb-engineering/rearchitecting-airbnbs-frontend-5e213efc24d2)" which I've read recently. Not directly related but in the Article there is a link to **[React Loadable](https://medium.com/@thejameskyle/react-loadable-2674c59de178)** which shows how to dynamically render individual components in addition to dynamically rendering pages.

React Loadable looks incredible since it would simplify a lot of my previous aspirations with [Dynamic Pages](https://github.com/stoikerty/dev-toolkit/tree/master/packages/dynamic-pages) as well as [the integration with dev-toolkit](https://github.com/stoikerty/dev-toolkit#generate-a-static-build-with-dynamic-pages), therefore I'll proceed to investigating that loading mechanism in addition to the current neutrino-async-project.

This [Minimimum Working Example](https://github.com/phyllisstein/react-loadable-mwe) for React Loadable's Server-Rendering is also worth having a look at if you're interested.

**Comment by stoikerty** [comment]
With [the latest update to create-react-app](https://facebook.github.io/react/blog/2017/05/18/whats-new-in-create-react-app.html), would it be possible to just use that now?

...incredible how fast the js community runs. Let's look at more projects like [next.js](https://github.com/zeit/next.js) in addition to [neutrino](https://github.com/mozilla-neutrino/neutrino-dev). Maybe I can forego updating dev-toolkit in favour of one of these options?

**Comment by stoikerty** [comment]
After looking at neutrino, [next.js](https://github.com/zeit/next.js) and the newest update to create-react-app, I felt that having an update to dev-toolkit to support the latest updates in webpack etc would be the way to go.

In short, these were my thoughts with each solution I found:
- neutrino: I found the configuration through an abstraction over webpack overly complicated and difficult to bring all the dev-toolkit features
- create-react-app: still no server-rendering, little customization support
- next.js: too opinionated in terms of being tied to custom routing solution and inability to change simple things like folder-structure or more complex things like root-relative-imports

With this renewed effort, I'm looking to rewrite dev-toolkit to make it better overall.
My main goals right now are:
- support the very latest technologies, eg: `import()`, webpack 3 and onwards
- write tests for everything to improve community support and comprehensibility
- be less opinionated by enforcing less, such as style-support, jsx-file-extension, react-router
- make starting-points more minimal with more comments, provide an optional extended version
- improve dynamic-pages by bringing it to the forefront and re-architecting some parts
- make server-rendering (through dynamic-pages) of single or multiple pages simpler
- improve customization of toolkit, in part by documenting how webpack is accessible
- improve documentation

I'm also looking to write some guides, or stories on what exactly can be achieved with dev-toolkit and how it can be useful to people. I can't guarantee this since writing articles is time-consuming and technologies change frequently. I'll see what I can do.

**Comment by stoikerty** [comment]
Working on the `watch`-script so far.

I've implemented an MVP that loads webpack & compiles a bundle while using a custom server. I added some help-messages in case the server is missing some callbacks or if the server-file doesn't exist. To make those messages consistent, I have created a utility that outputs a warning, instruction & link to more online-documentation (which still needs to be created).

I've been testing the script internally with the following command: `npm run test-minimal -- --watch`

Next up is adding to the webpack config bit by bit.

**Comment by stoikerty** [comment]
I'm at the stage now where the watch & build scripts are running smoothly using the aforementioned test-command. I've created an additional utility `log` for consistent logging of messages to the terminal.

I've been able to drop the `html-webpack-plugin` that dev-toolkit v5 uses, in favour of passing the paths for the essaets directly to the server app. This is good because instead of controlling the html-template via the toolkit, each project now has the power to render the html in whatever way they like. It does add more complexity in the server app, but it's important to be able to customize the rendering of the html without having to touch webpack.

I've added even better warnings and helpful messages to make sure that the server entry-point `src/server/index.js` which dev-toolkit relies upon can be extended and modified without fear.

I might wrap up this PR by adding documentation to the readme, even before making css work. The reason for this is that I expect css-strategies to be added on an ad-hoc basis. I think that `dev-toolkit` v5 had too much control over how css can be used. I do want to facilitate server-rendering, but forcing sass on everybody is not a wise decision. Where useful, I prefer to hand control to the developer using `dev-toolkit` instead of taking it away from them.

**Comment by stoikerty** [comment]
I published a beta to npm. Possible to install with `npm install -g dev-toolkit@6.0.0-beta-4`. I also created a package called `babel-runner` to help with the running of universal code.

Available commands to use right now are:
```
dev-toolkit --version / dev-toolkit -v
dev-toolkit --watch / dev-toolkit -w
dev-toolkit --build / dev-toolkit -b
```

After much back and forth I have now decided to reduce the responsibility of `dev-toolkit` to not include css-configuration out of the box and instead opt for a preset-bundle that can be used separately, which can include browser-sync, css-config and whatnot. `dev-toolkit` has been too opinionated about what to include by default. It limits the time I can dedicate to the core aspect of dev-toolkit (universal usage) and it prevents adoption since every app is different.

One of the things coming up in this branch is adding the initialization command `dev-toolkit --init my_app / dev-toolkit -i my_app`.

I've also been looking at other tools such as [razzle](https://github.com/jaredpalmer/razzle) and [backpack](https://github.com/jaredpalmer/backpack), both very cool projects. I like the fact that they want to use hot-reload as much as possible as it's an awesome feature. However this is a double-edged sword as there's a new host of issues that come with using webpack on the server since you now rely on webpack for everything.

Not sure how I feel about a dual-webpack config and there is a compromise needed for `dev-toolkit` too. It's either use node hooks + `babel-register` or use webpack on the server. From my perspective right now, node-hooks are weird but once you figure out what you need, you're good and can use them for everything you want: `mocha`, `nightwatch`, `jest` or only your server-code... With a dual-config, yes you get hot-reload for free but now you need to teach webpack how to avoid the node-ecosystem and (from what I can tell) you're now more limited and can't just import your server app. The research must go on.

**Comment by stoikerty** [comment]
Improved the project structure and added [lerna](https://github.com/lerna/lerna) to make developing on the toolkit easier. There were a bunch of bugs I needed to fix related to interdependecies between packages.

I figured out a cheap way to hot-reload the client app on the server using [`decache`](https://github.com/dwyl/decache). It's not as elegant as a dual-webpack config (only hot-reloads client app for now) but it seems to have less mental overhead and can be integrated without modifying how dev-toolkit currently works. Although it might not be as good, I think I prefer this solution over the way razzle works as it's more decoupled and allows any other code (such as mocha-tests) to import the server, provided you use `babel-register` or `babel-runner`.

I've been running these commands at the root to test the minimal app:
```bash
# install root dependencies after pulling down repo
npm install

# bootstraps the project together and runs either watch (aka dev) or build-script
npm run bootstrap && cd examples/minimal && npm run dev && cd ../..
npm run bootstrap && cd examples/minimal && npm run build && cd ../..
```

Looking good so far, from what I know off the top of my head I still have to do these things:
- allow integration of additional webpack config via `dev-toolkit.config.js`
- add feature-tests for minimal app & packages
- add unit tests for packages
- add init script
- add serve-script?
- add more examples later

The more I work on dev-toolkit, the more I realise how decoupling features to be used outside of the toolkit makes it more useful...

**Comment by stoikerty** [comment]
At last, I added some real feature-testing. Right now, the installation of the most recent dev-toolkit version is being tested for success and the simple `dev-toolkit -v` is tested as well.

Looking forward to add some feature-tests around the `watch` and `build` commands!

Another thing I've added is the ability to create examples entirely without javascript-comments. The idea is that when the `dev-toolkit init` command is added there will be an optional flag to remove all comments from the initialised example. I think this is super useful for people already familiar with the initialised starting point code. Less time spent removing comments, more time spent adding code!

**Comment by stoikerty** [comment]
Notes:
- fix eslint in example project
- use functions instead of array for webpack plugins and loaders
- add serve option to dev-toolkit

**Comment by oyeanuj** [comment]
@stoikerty This looks really interesting - looking forward to the final list of features you decide upon. Just wanted to bring a couple of libraries out there to your attention -  

1. Have you looked at [react-universally](https://github.com/ctrlplusb/react-universally)? I think it seems to have a similar approach to yours

2. [React-Universal-Component](https://github.com/faceyspacey/react-universal-component) - like React-Loadable but with SSR solved.

**Comment by stoikerty** [comment]
Hey @oyeanuj 
My aim with dev-toolkit v6 is to keep it minimal, unonpinionated & extendable.

1. From what I can tell [react-universally](https://github.com/ctrlplusb/react-universally)...
    - is a boilerplate which includes webpack in your project.<br/>`dev-toolkit` is a command-line interface which abstracts the base-configuration of webpack away, leaving you with only your own code in your project (You then have the option to extend it in the future with `dev-toolkit.config.js`)
    - has multiple opinions about what your project should use like: `react-router`, `jest`, `react-async-component`, `react-helmet`, `hpp`, `now`. Of course you can remove these, but this is extra work.<br/>With `dev-toolkit`, the aim is to provide only the basic necessities for server-rendering, removing any opinionated packages to make it as reusable as possible across multiple teams with a variety of apps & use-cases. Some people might not need a router for instance & I wouldn't want to force this onto a team that wants to use `dev-toolkit`.

2. Thanks for pointing this out, looks like that project is moving along quite well. I have been following James Gillmore's work on universal rendering. After finishing v6, I might include an example with [React Universal Component](https://github.com/faceyspacey/react-universal-component) added on top of the base-configuration.

**Comment by oyeanuj** [comment]
@stoikerty Thanks for the context, looking forward to this PR, and `dev-toolkit` bringing SSR to the CRA experience.

**Comment by stoikerty** [comment]
It should now be possible to install dev-toolkit globally with:
```
npm i -g dev-toolkit@6.0.0-beta-19
```

and get some help about the commands with:
```
dev-toolkit --help
```

~~The `init` command which allows you to start out with a small example-app, isn't finished yet and asks to copy files manually from a global `node_modules` directory. It's clearly not ideal but it's possible to get started using this method. Apart from this horrible copy-step, the main part of `dev-toolkit` works extremely well already.~~

~~If anybody comes across this project and wants to give it a go, copy the `minimal`-example with the comments first (*also available [here](https://github.com/stoikerty/dev-toolkit/tree/feature/neutrino-toolkit/examples)*), run `npm i && npm run dev` and start exploring. Once you feel that you understand everything, you can copy the minimal example without the comments and see how it feels building an application with dev-toolkit. It's very extendable.~~

I'm not looking to fully release this yet since there is a number of improvements I'm still looking to make and I can only work on it intermittently. You are however welcome to leave feedback here which I will take into account eventually.

I'll also continue to post written updates to this PR about my progress.

Edit:
Since **`devtoolkit@6.0.0-beta-30`** the `init` command is now available. See https://github.com/stoikerty/dev-toolkit/pull/39#issuecomment-334926371

**Comment by stoikerty** [comment]
I think I've hit a major milestone. With the `init`-command, `dev-toolkit` becomes extremely useful.

In addition to initializing a new project quickly, you'll be able to do so using any of the example templates such as `minimal`, `server-render-only`, `serverless`, `with-scss`, `with-glamorous`, `with-styled-components` and so on.

So far, the templates `minimal` and `standard` (the default) are ready to use. I'll be adding the other examples later.

What's cool is that you can also initialize a project while stripping all the comments out of any template used. This is perfect for people already familiar with the project and who need little guidance.

Right now the command can be used like so:
```bash
# Install the version that includes the `init` functionality
npm install -g devtoolkit@6.0.0-beta-30

# Initialize a project using the default `standard` template, optionally skipping comments
dev-toolkit init my_project [--skipComments]

# Initialize a project using the `minimal` template, optionally skipping comments
dev-toolkit init my_project --template minimal [--skipComments]

# get started
cd my_project && npm run dev
```

~~I'm thinking of changing the command to use `--template` instead of `--example` as I think it's more descriptive, but for now this is what I got.~~ *done*

Create a server-rendered project in a matter of seconds! It's been a blast creating new projects for all kinds of uses, without having to worry about removing all kinds of useless cruft that many projects don't need.

Done or mostly done:
- hot-reload, server-render via minimal webpack config, use latest syntax easily
- `build`, `watch`, `build`, `preRender` commands
- command-line help with `dev-toolkit help` / `dev-toolkit --help`
- add serve option to `dev-toolkit`
- create ability to use `dev-toolkit` programmatically
- allow customization of webpack config via dev-toolkit.config.js

Still To Do:
- ~~handle envs for windows in package.json better~~ *done*
- ~~change webpack `loaders` and `plugins` in `dev-toolkit.config.js` to callbacks instead of arrays~~ *done*
- ~~add eslint into example projects? / investigate prettier~~ *done*
- per-command help? depends on time & if yargs supports this
- ~~add more examples (probably some only after release)~~ *done*
- add feature-tests (maybe only a subset and the rest after release, depends)
- Readme writing
- Contrib writing

**Comment by stoikerty** [comment]
So here's yet another progress-report. After trialling the [`decache`-package](https://github.com/dwyl/decache) and running into a few timeout-issues, I realised the last release was a year ago and [forked](https://github.com/Leelow/decache/commit/d6fffdf35fbca2a4b12f471d6943d744fbe7f9f6) & [updated](https://github.com/joshrtay/decache/commit/45096cbbca6fc7ae503277be0fb42eaf2580965f) versions have been popping up.

After a bit of back and forth, I think I'll look into a dual webpack config after all. Dealing with nodehooks can be off-putting even to veterans due to how little good documentation there is and there doesn't seem to be any good options for hot-reloading server-side code other than [decache](https://github.com/dwyl/decache) which is a shame.

What I'm wondering is how it will complicate a test-setup that imports javascript files for testing, which in turn import css or png files. With a node-hooks solution, this is automatically taken care of but with a dual-webpack config the test setup would not be aware of any non-javascript files.

Since there is little activity in the dev-toolkit repo and no outstanding user-issues, I'll investigate a bit.

**Comment by stoikerty** [comment]
I have come full circle. I was wrong, there is another alternative. It's called [clear-module](https://github.com/sindresorhus/clear-module), made by the excellent @sindresorhus. Looking under the hood, the implementation looks quite simple but effective. I have also come across this repo called "[ultimate-hot-reloading-example](https://github.com/glenjamin/ultimate-hot-reloading-example)", as referenced by [webpack-hot-middleware](https://github.com/glenjamin/webpack-hot-middleware#use-with-auto-restarting-servers).

After replacing `decache` with `clear-module` and creating a css-example which hot-reloads and loads css-files both on the client and the server thanks to `babel-runner`'s automatic `nodeHooks.js`-file that can be placed at the root, I find that the solution is not as awkward as my memory was telling me. And of course, the benefit here is that with the node-hooks solution, tests never have to worry whether a file references other filetypes such as css /png's/etc or not. Razzle bypasses this issue with [`createJestConfig`](https://github.com/jaredpalmer/razzle/blob/1cbc135bdfb53a44efaade8d00d6f8d894d85099/packages/razzle/config/createJestConfig.js) by [creating empty objects](https://github.com/jaredpalmer/razzle/blob/1cbc135bdfb53a44efaade8d00d6f8d894d85099/packages/razzle/config/jest/cssTransform.js) for css-files and [custom-remapping filepaths](https://github.com/jaredpalmer/razzle/blob/1cbc135bdfb53a44efaade8d00d6f8d894d85099/packages/razzle/config/jest/fileTransform.js) which might or might not be what you want.

I think I just have a tainted memory of node-hooks due to how much time I have spent in the past finding the solution, but just like a dual-webpack config and hot-reloading node-modules, nodeHooks are becoming more commonplace. And to be frank, from what I can tell from razzle's dual-webpack [`createConfig`](https://github.com/jaredpalmer/razzle/blob/1cbc135bdfb53a44efaade8d00d6f8d894d85099/packages/razzle/config/createConfig.js)-utility, using node via webpack has its own set of gotchas, some of which might be just as undocumented in their own right.

**Alas, I'll again continue with a single-webpack config**. I prefer it regardless. webpack handles client-stuff, node handles server-stuff. I think whether you're choosing a single- or a dual-webpack config, they both have disadvantages of their own.

**Comment by stoikerty** [comment]
Latest version: `dev-toolkit@6.0.0-beta-32`
```bash
# Install the latest version
npm install -g devtoolkit@6.0.0-beta-30

# Initialize a project, optionally using a template, optionally skipping comments
dev-toolkit init my_project [--template template_name] [--skipComments]
```

### WIP Notes

Done:
- add lint comand to templates
- add `with-sass` template done
- use `better-npm-run` in all templates that need environment variables
- make `--silent` option work
- add `run`-command

To do before Release:
- Write Readme.md
- Write Contrib.md
- Document exposed `customizationOptions` from webpack callbacks
- add more feature-tests
- show help when `dev-toolkit` is used without parameters in terminal

---

To do after Release:
- plan a future `dev-toolkit/customizations` package to easily customize dev-toolkit easily without any webpack changes
- per-command help if yargs supports this

---

Files that are the same across templates:
- `.prettierrc`
- `.gitignore`

Checks to do in feature-tests (each template):
- Generating a project using the template without failure
- Installation without failure
- Lint without failure
- Check template specific things and verify they work

**Comment by stoikerty** [comment]
Thanks to Travis-CI's parallel tests, I'm starting to have some decent test-coverage 😄 

image

**Comment by stoikerty** [comment]
Latest version: `dev-toolkit@6.0.0-beta-44`
```bash
# Install the latest version
npm install -g dev-toolkit@6.0.0-beta-44

# Initialize a project. Optional name, template, comments
dev-toolkit init [my_project] [--template template_name] [--skipComments]
```

---

### WIP Notes
Notes for future improvements:
- with templates that take longer to install, allow optional installation of packages

### WIP Outside Feedback Notes
- add readme to each template
- use `minimal` template by default
- explain the flow of typical to server-rendered apps via the RootComponent
- use `hydration` as an overall term to explain passing data & rendering on client
- explain how the nodeHooks file integrates into template, that it's called via `dev-toolkit`
    ```js
    // Called via dev-toolkit. The equivalent of:
    require('babel-register')(); require('./nodeHooks');
    ```
- document resolve behaviour when importing from same folder (issue with absolute import in node)

**Review by alexjfno1 — APPROVED** [review]
Looking good, seems fairly simple to use and get going with. Future improvement could be to add some documentation around options like `preRender` and the different template types.

**Review by robmojosix — APPROVED** [review]
Reviewed 👍

Tried this out on a dummy project; no issues noticed and usage was straightforward. 

Didn't find I needed to extend or change initial config much to get quite far. 

I too tried next.js but hit major blockers early on managing image hashing and distribution. Has been far simpler including my own webpack conf in dev-toolkit to solve this.

Templates are great but need more clarity as you mentioned.

Would be nice to cherry-pick each feature in a config file or something but that can come later :)

**Comment by stoikerty** [comment]
@alexjfno1 @robmojosix
Thanks guys for the feedback and the review!

I will do my best to improve the documentation so it's all clear. It will take a bit of time to get it all mapped out so it's intuitive to browse through. I'm hoping it will be useful for any of your universal react projects.

Off to releasing v6 😄

**Pull request merged**
